# Generated by Django 3.0.3 on 2020-02-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200212_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sex',
            new_name='stu_gender',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='depart',
        ),
        migrations.AlterField(
            model_name='student',
            name='teacher',
            field=models.ManyToManyField(blank=True, null=True, to='web.Teacher', verbose_name='任课老师'),
        ),
        migrations.DeleteModel(
            name='Depart',
        ),
    ]
