# Generated by Django 3.0.3 on 2020-02-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200212_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='free_time',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='空余时间,格式：周日 8点-12点'),
        ),
    ]
