# Generated by Django 3.0.3 on 2020-02-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_teacher_free_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='free_time',
            field=models.CharField(default=1, max_length=128, verbose_name='空余时间'),
            preserve_default=False,
        ),
    ]
