# Generated by Django 3.0.3 on 2020-02-13 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20200212_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Customer', verbose_name='客户信息'),
        ),
    ]
