# Generated by Django 3.0.3 on 2020-02-13 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20200213_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teacher',
            field=models.ManyToManyField(blank=True, null=True, to='web.Teacher', verbose_name='任课老师'),
        ),
    ]
