# Generated by Django 3.0.3 on 2020-02-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20200213_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='pay_type',
            field=models.IntegerField(choices=[(1, '学费'), (2, '退费'), (3, '其他')], default=1, verbose_name='缴费类型'),
        ),
    ]
