# Generated by Django 3.0.3 on 2020-02-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_paymentrecord_pay_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='pay_type',
            field=models.IntegerField(choices=[(1, '学费'), (2, '试听'), (3, '退费'), (4, '其他')], default=1, verbose_name='缴费类型'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='账号'),
        ),
    ]
